---
printWidth: 100
tabWidth: 4
useTabs: false
trailingComma: all
semi: true
singleQuote: false
plugins:
    - prettier-plugin-organize-imports
    - prettier-plugin-svelte
overrides:
    - files: "*.svelte"
      options:
          parser: svelte
